version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
      - run:
          name: Install chisel
          command: cargo install chisel
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Build
          command: |
            cargo build --release
            chisel run
      - run:
          name: Tests
          command: cargo test --target=x86_64-unknown-linux-gnu
